version: "2.2"
services:
  app:
    container_name: quill
    build: .
    ports:
      - "3000:3000"
      - "5858:5858"
      - "8080:8080"
      - "35729:35729"
    environment:
      - NODE_ENV=dev
      - DATABASE=mongodb://myquill_db_1:27017
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASS=party
      - EMAIL_CONTACT=Hackathon Team <team@example.com>
      - EMAIL_HOST=smtp.example.com
      - EMAIL_USER=no-reply@example.com
      - EMAIL_PASS=password
      - EMAIL_PORT=465
      - EMAIL_HEADER_IMAGE=https://s3.amazonaws.com/hackmit-assets/Banner_600.jpg
    depends_on:
      - db
    volumes_from:
      - web-data
  web-data:
    build: .
    entrypoint: /bin/true
    volumes:
      - ./:/opt/mean.js
      - /opt/mean.js/node_modules
      - /opt/mean.js/public
      - /opt/mean.js/uploads
  db:
    image: mongo
    volumes_from:
      - db-data
    ports:
      - "27017:27017"
  db-data:
    image: mongo
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
